AWSTemplateFormatVersion: 2010-09-09
Description: cfn api gateway alarms
Parameters:
  awsEnv:
    Type: String
    Default: dev
  snsTopicAlarmArn:
    Type: String
  apiName:
    Type: String          
Resources:         
  # api gateway Alarms
  api4XXErrorAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub ${apiName}-4XXError-alert-${awsEnv}
      AlarmDescription: !Sub ${apiName}-4XXError-alert-${awsEnv}
      AlarmActions:
        - !Ref snsTopicAlarmArn
      MetricName: "4XXError"
      Namespace: "AWS/ApiGateway"
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 5
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref apiName
  api5XXErrorAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub ${apiName}-5XXError-alert-${awsEnv}
      AlarmDescription: !Sub ${apiName}-5XXError-alert-${awsEnv}
      AlarmActions:
        - !Ref snsTopicAlarmArn
      MetricName: "5XXError"
      Namespace: "AWS/ApiGateway"
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 5
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref apiName
  apiCacheMissAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub ${apiName}-cachemiss-alert-${awsEnv}
      AlarmDescription: !Sub ${apiName}-cachemiss-alert-${awsEnv}
      AlarmActions:
        - !Ref snsTopicAlarmArn
      MetricName: "CacheMissCount"
      Namespace: "AWS/ApiGateway"
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 5
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref apiName
  apiIntegrationLatencyAlert:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub ${apiName}-integrationlatency-alert-${awsEnv}
      AlarmDescription: !Sub ${apiName}-integrationlatency-alert-${awsEnv}
      AlarmActions:
        - !Ref snsTopicAlarmArn
      MetricName: "IntegrationLatency"
      Namespace: "AWS/ApiGateway"
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 5
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref apiName 
  # Api Gateway Anamoly
  apiAnomalyDetectorOnCount:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: "Count"
      Namespace: "AWS/ApiGateway"
      Stat: Sum
      Dimensions:
        - Name: ApiName
          Value: !Ref apiName
  apiAnomalyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub ${apiName}-count-alert-${awsEnv}
      AlarmName: !Sub ${apiName}-count-alert-${awsEnv}
      AlarmActions:
        - !Ref snsTopicAlarmArn
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 1
      Metrics:
      - Expression: ANOMALY_DETECTION_BAND(m1, 2)
        Id: ad1
      - Id: m1
        MetricStat:
          Metric:
            MetricName: Count
            Namespace: AWS/ApiGateway
          Period: !!int 86400
          Stat: Sum
      ThresholdMetricId: ad1        
        
   # CW Dashboard
  cwApiGtwDashboard:
    Type: "AWS::CloudWatch::Dashboard"
    Properties:
      DashboardName: !Sub ${apiName}-cw-api-gtw-dashboard-${awsEnv}
      DashboardBody: !Sub '{"widgets":[{"type":"metric","x":0,"y":0,"width":12,"height":6,"properties":{"metrics":[["AWS/ApiGateway","4XXError","ApiName","${apiName}"]],"period":60,"stat":"Sum","region":"${AWS::Region}","title":"Api Gateway 4xxError"}},{"type":"metric","x":12,"y":0,"width":12,"height":6,"properties":{"metrics":[["AWS/ApiGateway","5XXError","ApiName","${apiName}"]],"period":60,"stat":"Sum","region":"${AWS::Region}","title":"Api Gateway 5xxError"}},{"type":"metric","x":0,"y":12,"width":12,"height":6,"properties":{"metrics":[["AWS/ApiGateway","IntegrationLatency","ApiName","${apiName}"]],"period":60,"stat":"Sum","region":"${AWS::Region}","title":"Api Gateway IntegrationLatency"}}]}'

                                        